<meta name='viewport' content='width=device-width, initial-scale=1.0'>

<link rel="shortcut icon" href="asset/img/icon/favicon.ico" type="image/x-icon">

<!-- http://scottjehl.github.io/picturefill/ -->
<script>
    document.createElement("picture");
</script>
<script src="asset/lib/js/picturefill.min.js" async></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<!-- My Custom Javascript and CSS -->

<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.19/css/uikit.min.css"> -->
<link rel="stylesheet" href="asset/css/styles.css">


<!-- jQuery -->
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript" src="asset/js/script2.js" async></script>
<script src="asset/lib/ism/js/ism-2.2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.19/js/uikit.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.19/js/uikit-icons.min.js"></script>



