<header class="main-header">
    <h1 class="site-title">Travel</h1>
    <h1 class="site-title">Wave</h1>
    <div class="searchbox-desktop">
        <form>
            <input type="text" placeholder="Search..." required>
            <input type="button" class="search-btn uk-button-secondary" value="Search">
        </form>
    </div>

    <div id="cssmenu">
        <ul>
            <li><a href="#"><span><i class="fa fa-fw fa-bars"></i> Places</span></a>
                <ul>
                    <li><a href="/hawaii"><span>Hawaii</span></a></li>
                    <li><a href="/boracay"><span>Boracay</span></a></li>
                    <li><a href="/manila"><span>Manila</span></a></li>
                </ul>
            </li>
            <li><a href="#"><span><i class="fa fa-fw fa-paper-plane"></i> Travel Services</span></a></li>
            <li><a href="#"><span><i class="fa fa-fw fa-phone"></i> Contact</span></a></li>
            <li><a href="/registration"><span><i class="fa fa-fw fa-street-view"></i> Registration</span></a></li>
        </ul>
    </div>
</header>





