<footer class="footer">
    <div class="searchbox-mobile uk-width-1-1@s">
        <form>
            <input type="text" placeholder="Search..." required>
            <input type="button" class="search-btn" value="Search">
        </form>
    </div>

    <div class="foot-menu-grp  uk-container uk-align-center">


        <div class="uk-grid-small" uk-grid>
            <div class="foot-menu uk-width-1-5@l uk-width-1-4@m uk-width-1-2@s">
                <ul>
                    <li><h3>Places</h3></li>
                    <li><a href="/hawaii"><span>Hawaii</span></a></li>
                    <li><a href="/boracay"><span>Boracay</span></a></li>
                    <li><a href="/manila"><span>Manila</span></a></li>
                </ul>
            </div>
            <div class="foot-menu uk-width-1-5@l uk-width-1-4@m uk-width-1-2@s">
                <ul>
                    <li><h3>Content</h3></li>
                    <li><a href="#">Travel Services</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div>
            <div class="foot-menu uk-width-1-5@l uk-width-1-4@m uk-width-1-2@s">
                <ul>
                    <li><h3>Follow Us</h3></li>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">YouTube</a></li>
                </ul>
            </div>
            <div class="foot-menu uk-width-1-5@l uk-width-1-4@m uk-width-1-2@s">
                <ul>
                    <li><h3>Legal</h3></li>
                    <li><a href="#">Terms and Conditions</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="foot-menu uk-width-1-5@l uk-width-1-4@m uk-width-1-2@s">
                <ul>
                    <li><h3>Thanks to</h3></li>
                    <li><a href="http://www.bigstockphotos.com" target="_blank">Big Stock Photos</a></li>
                    <li><a href="http://www.1001freefonts.com" target="_blank">Google Fonts </a></li>
                    <li><a href="https://scottjehl.github.io/picturefill/" target="_blank">Picturefill.js</a></li>
                </ul>
            </div>
        </div>

        <div class="uk-grid-small" uk-grid>
            <div class="copyright uk-width-1-1 uk-align-center">
                <p class="copyright-text">Copyright © 2017 / DGMD E-27 * A Student Project by Jai</p>
            </div>
        </div>
    </div>

</footer>
